// Traducción de consultas de búsqueda de emoji ES → EN.
//
// El buscador de emoji (emoji-mart, vía BlockNote) sólo indexa palabras clave en
// inglés, así que escribir «fuego» o «corazón» no devuelve nada. Aquí mapeamos
// los términos más habituales en español a su equivalente inglés antes de buscar.
// Las claves se guardan SIN acentos y en minúsculas; la búsqueda normaliza igual.

/** Quita acentos/diacríticos y pasa a minúsculas para comparar de forma laxa. */
function norm(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}

// Mapa palabra(es) → término(s) de búsqueda en inglés.
const ES_EMOJI: Record<string, string> = {
  // Caras y emociones
  cara: "face",
  sonrisa: "smile",
  sonriente: "smile",
  feliz: "happy smile",
  felicidad: "happy",
  contento: "happy",
  alegre: "happy",
  risa: "laughing",
  riendo: "laughing",
  jaja: "laughing",
  carcajada: "rolling laughing",
  triste: "sad",
  tristeza: "sad cry",
  llorar: "cry",
  llorando: "cry",
  lagrima: "cry tear",
  lagrimas: "cry tear",
  enojado: "angry",
  enfadado: "angry",
  enfado: "angry",
  rabia: "angry rage",
  furioso: "rage angry",
  miedo: "fear scared",
  asustado: "scared fearful",
  sorpresa: "surprised",
  sorprendido: "surprised astonished",
  guino: "wink",
  beso: "kiss",
  enamorado: "heart eyes love",
  amor: "love heart",
  pensando: "thinking",
  pensar: "thinking",
  dormir: "sleeping",
  durmiendo: "sleeping",
  sueno: "sleeping",
  cansado: "tired",
  enfermo: "sick ill",
  mareado: "dizzy",
  vomito: "vomit",
  guay: "cool sunglasses",
  genial: "cool",
  gafas: "sunglasses",
  nervioso: "nervous sweat",
  preocupado: "worried",
  confundido: "confused",
  serio: "neutral",
  payaso: "clown",
  fantasma: "ghost",
  calavera: "skull",
  craneo: "skull",
  muerte: "skull death",
  diablo: "devil imp",
  angel: "angel",
  alien: "alien",
  extraterrestre: "alien",
  robot: "robot",
  caca: "poop",
  guino_ojo: "wink",

  // Gestos y partes del cuerpo
  pulgar: "thumbs up",
  pulgares: "thumbs up",
  mano: "hand",
  manos: "hands",
  aplausos: "clap",
  aplaudir: "clap",
  palmas: "clap",
  rezar: "pray",
  orar: "pray",
  musculo: "muscle",
  fuerza: "muscle",
  ojo: "eye",
  ojos: "eyes",
  oreja: "ear",
  nariz: "nose",
  boca: "mouth",
  lengua: "tongue",
  cerebro: "brain",
  corazon: "heart",
  pie: "foot",
  bebe: "baby",
  nino: "child boy",
  nina: "child girl",
  hombre: "man",
  mujer: "woman",
  familia: "family",
  corona: "crown",
  rey: "crown king",
  reina: "crown queen",

  // Naturaleza y clima
  fuego: "fire",
  estrella: "star",
  estrellas: "star sparkles",
  sol: "sun",
  luna: "moon",
  nube: "cloud",
  nubes: "cloud",
  lluvia: "rain",
  nieve: "snow",
  rayo: "zap lightning",
  relampago: "lightning",
  arcoiris: "rainbow",
  flor: "flower",
  flores: "flowers",
  rosa: "rose",
  arbol: "tree",
  arboles: "tree forest",
  planta: "plant seedling",
  hoja: "leaf",
  hojas: "leaves",
  cactus: "cactus",
  agua: "water droplet",
  gota: "droplet",
  ola: "wave",
  mar: "ocean wave",
  montana: "mountain",
  volcan: "volcano",
  tierra: "earth globe",
  mundo: "earth globe world",

  // Animales
  perro: "dog",
  gato: "cat",
  raton: "mouse",
  conejo: "rabbit",
  oso: "bear",
  panda: "panda",
  koala: "koala",
  leon: "lion",
  tigre: "tiger",
  vaca: "cow",
  cerdo: "pig",
  caballo: "horse",
  oveja: "sheep",
  cabra: "goat",
  pollo: "chicken",
  gallina: "chicken hen",
  pajaro: "bird",
  ave: "bird",
  pez: "fish",
  pescado: "fish",
  ballena: "whale",
  delfin: "dolphin",
  tiburon: "shark",
  pulpo: "octopus",
  tortuga: "turtle",
  serpiente: "snake",
  mono: "monkey",
  abeja: "bee",
  mariposa: "butterfly",
  arana: "spider",
  pinguino: "penguin",
  pato: "duck",
  aguila: "eagle",
  buho: "owl",
  rana: "frog",
  caracol: "snail",
  hormiga: "ant",
  dinosaurio: "dinosaur",
  dragon: "dragon",
  unicornio: "unicorn",
  zorro: "fox",
  lobo: "wolf",
  elefante: "elephant",
  jirafa: "giraffe",
  cebra: "zebra",

  // Comida y bebida
  comida: "food",
  pizza: "pizza",
  hamburguesa: "hamburger",
  cafe: "coffee",
  te: "tea",
  cerveza: "beer",
  vino: "wine",
  copa: "wine glass",
  pastel: "cake",
  tarta: "cake",
  cumpleanos: "birthday cake",
  helado: "ice cream",
  manzana: "apple",
  platano: "banana",
  fresa: "strawberry",
  uva: "grapes",
  uvas: "grapes",
  naranja: "tangerine orange",
  limon: "lemon",
  sandia: "watermelon",
  pan: "bread",
  queso: "cheese",
  huevo: "egg",
  carne: "meat",
  arroz: "rice",
  chocolate: "chocolate",
  caramelo: "candy",
  dulce: "candy sweet",
  galleta: "cookie",
  palomitas: "popcorn",
  taco: "taco",
  sushi: "sushi",

  // Objetos, símbolos y actividades
  regalo: "gift present",
  dinero: "money",
  plata: "money",
  fiesta: "party tada",
  globos: "balloon",
  reloj: "clock watch",
  telefono: "phone",
  movil: "mobile phone",
  celular: "mobile phone",
  ordenador: "computer laptop",
  computadora: "computer laptop",
  libro: "book",
  libros: "books",
  musica: "music note",
  nota: "note",
  camara: "camera",
  foto: "camera photo",
  pelicula: "movie film",
  juego: "game",
  futbol: "soccer",
  baloncesto: "basketball",
  tenis: "tennis",
  pelota: "ball",
  balon: "ball soccer",
  trofeo: "trophy",
  medalla: "medal",
  correr: "running",
  bailar: "dancing",
  baile: "dancing",
  nadar: "swimming",
  bandera: "flag",
  bombilla: "bulb idea",
  idea: "bulb idea",
  candado: "lock",
  llave: "key",
  bomba: "bomb",
  cohete: "rocket",
  coche: "car",
  auto: "car automobile",
  carro: "car",
  avion: "airplane",
  tren: "train",
  barco: "ship boat",
  bicicleta: "bicycle",
  moto: "motorcycle",
  casa: "house home",
  trabajo: "office briefcase work",
  oficina: "office",
  escuela: "school",
  calendario: "calendar",
  carpeta: "folder file",
  basura: "trash",
  papelera: "wastebasket trash",
  correo: "email envelope",
  email: "email envelope",
  sobre: "envelope",
  campana: "bell",
  vela: "candle",
  diana: "dart target",
  objetivo: "dart target",
  meta: "checkered flag goal",

  // Símbolos de marca/estado
  correcto: "check mark",
  bien: "check mark ok",
  visto: "check mark",
  error: "cross x",
  mal: "cross x",
  cruz: "cross x",
  advertencia: "warning",
  peligro: "warning danger",
  cuidado: "warning",
  pregunta: "question",
  duda: "question",
  exclamacion: "exclamation",
  prohibido: "no entry prohibited",
  flecha: "arrow",
  signo: "exclamation",
  ok: "ok",
};

// Claves ordenadas para que la coincidencia por prefijo sea determinista.
const ES_KEYS = Object.keys(ES_EMOJI).sort();

/** Traduce una sola palabra (normalizada) o devuelve `null` si no la conoce. */
function lookupWord(w: string): string | null {
  if (ES_EMOJI[w]) return ES_EMOJI[w];
  // Plural simple: «gatos» → «gato».
  if (w.endsWith("s") && ES_EMOJI[w.slice(0, -1)]) return ES_EMOJI[w.slice(0, -1)];
  // Prefijo: mientras se escribe, «fue» debe resolverse ya a «fire» (de
  // «fuego»); si no, el menú se cierra al no encontrar resultados intermedios
  // en inglés y no se reabre. Tomamos la primera clave que empiece por la
  // palabra.
  if (w.length >= 2) {
    const key = ES_KEYS.find((k) => k.startsWith(w));
    if (key) return ES_EMOJI[key];
  }
  return null;
}

/**
 * Traduce una consulta de búsqueda de emoji del español al inglés palabra por
 * palabra. Las palabras desconocidas se dejan tal cual (así el inglés y los
 * nombres latinos siguen funcionando).
 */
export function translateEmojiQuery(query: string): string {
  const words = query.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return query;
  return words.map((raw) => lookupWord(norm(raw)) ?? raw).join(" ");
}
